main:
  - name: Sobre
    url: "/#sobre"
    weight: 10
  - name: Publicações
    url: "/#publicacoes"
    weight: 20
  - name: Posts
    url: "/#posts"
    weight: 30
  - name: Projetos
    url: "/#projetos"
    weight: 40
