env: production
description: "Site pessoal de Leonardo Rodrigues, professor e pesquisador em sociologia da educação, educação superior e desigualdades sociais."
author: "Leonardo Rodrigues"
defaultTheme: auto
disableThemeToggle: false
ShowReadingTime: true
ShowShareButtons: false
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowRssButtonInSectionTermList: true
disableSpecial1stPost: true
mainSections:
  - post

profileMode:
  enabled: true
  title: "Leonardo Rodrigues"
  subtitle: "Professor e pesquisador em sociologia da educação, educação superior, desigualdades sociais e métodos quantitativos."
  imageUrl: "/avatar-small.jpg"
  imageTitle: "Leonardo Rodrigues"
  imageWidth: 160
  imageHeight: 160
  buttons:
    - name: Sobre
      url: "/#sobre"
    - name: Publicações
      url: "/#publicacoes"
    - name: Posts
      url: "/#posts"
    - name: Projetos
      url: "/#projetos"

socialIcons:
  - name: email
    url: "mailto:leonardoalr@gmail.com"
  - name: github
    url: "https://github.com/leonardoalr"
  - name: linkedin
    url: "https://www.linkedin.com/in/leonardo-lopesrodrigues/"
  - name: orcid
    url: "https://orcid.org/0000-0001-5176-5079"
  - name: x
    url: "https://twitter.com/Leoalr"
