[build]
command = 'hugo --noBuildLock'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.163.1'

[context]
[context.branch-deploy]
command = 'hugo --noBuildLock -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo --noBuildLock -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
